export const SUBIR_ENTUSIASMO ="SUBIR_ESTADO";
export type SUBIR_ENTUSIASMO=typeof SUBIR_ENTUSIASMO;

export const BAJAR_ENTUSIASMO ="BAJAR_ENTUSIASMO";
export type BAJAR_ENTUSIASMO=typeof BAJAR_ENTUSIASMO;

export const CHANGE_ENTUSIASMO="CHANGE_ENTUSIASMO"
export type CHANGE_ENTUSIASMO=typeof CHANGE_ENTUSIASMO
